import { Configuration, OpenAIApi } from 'openai'

// DO NOT PUBLIC THIS OR THE CLIENT WILL KNOW THE API KEY
// WE DO THIS BECAUSE WE ARE FOCUSING AT REACT AND TYPESCRIPT
// WE SHOULD CREATE AN API KEY FOR THIS
const apiKey = import.meta.env.VITE_OPENAI_API_KEY